version: "3.9"
services:
  database:
    image: mysql:8.0
    restart: on-failure
    environment:
      - "MYSQL_USER=kologermit"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_DATABASE=mygame"
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - "./db/mysql:/var/lib/mysql"
      - "./db-init.sql:/docker-entrypoint-initdb.d/create_tables.sql"
    ports:
      - "3306:3306"
    networks:
      - general

  client:
    build: ./client
    restart: always
    ports:
      - "80:8080"
    volumes:
      - "./client:/var/www/html/"
    networks:
      - general

networks:
  general:
    driver: bridge